// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGwD4DchpnWGg5_0h-hCgHXzEV_jlaxeQ',
    appId: '1:160008307714:web:ccf7fbe190d5722f68131b',
    messagingSenderId: '160008307714',
    projectId: 'tdm2023-2-b7953',
    authDomain: 'tdm2023-2-b7953.firebaseapp.com',
    storageBucket: 'tdm2023-2-b7953.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4t9b1k2tc88g3_zwxf6YLbkbO5-qxf3A',
    appId: '1:160008307714:android:6894255f4a8b0d0468131b',
    messagingSenderId: '160008307714',
    projectId: 'tdm2023-2-b7953',
    storageBucket: 'tdm2023-2-b7953.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBr-goec8oiUFyNe5WV8vkI8hOWVyjwGg',
    appId: '1:160008307714:ios:7f9e48d8ce6f1d1868131b',
    messagingSenderId: '160008307714',
    projectId: 'tdm2023-2-b7953',
    storageBucket: 'tdm2023-2-b7953.appspot.com',
    iosBundleId: 'com.example.appchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBr-goec8oiUFyNe5WV8vkI8hOWVyjwGg',
    appId: '1:160008307714:ios:5e7a295d41be370a68131b',
    messagingSenderId: '160008307714',
    projectId: 'tdm2023-2-b7953',
    storageBucket: 'tdm2023-2-b7953.appspot.com',
    iosBundleId: 'com.example.appchat.RunnerTests',
  );
}
